spring:
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    locations: classpath:db/migration

management:
  endpoints:
    web:
      exposure:
        include:
          - metrics
          - health
  endpoint:
    metrics:
      enabled: true

retry:
  providerA:
    maxAttempts: 3
    delay: 1000
    multiplier: 2.0
    maxDelay: 5000
  providerB:
    maxAttempts: 5
    delay: 1500
    multiplier: 1.5
    maxDelay: 10000

resilience4j:
  circuitbreaker:
    instances:
      providerA:
        registerHealthIndicator: true
        slidingWindowSize: 3
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 2
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
      providerB:
        registerHealthIndicator: true
        slidingWindowSize: 2
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 2
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
